-- Sample courses that match the purchased courses in orders table
-- Run this to add courses that members have purchased

INSERT INTO courses (
  name,
  instructor, 
  fees,
  duration,
  level,
  description,
  video_link,
  prerequisites,
  learning_outcomes,
  category,
  language,
  max_students,
  includes_certificate,
  status
) VALUES 
(
  'Introduction to Machine Learning',
  'Dr. Sarah Johnson',
  2999.00,
  '8 weeks',
  'Beginner',
  'Learn the fundamentals of machine learning including supervised and unsupervised learning algorithms. This comprehensive course covers linear regression, decision trees, clustering, and neural network basics.',
  'https://www.youtube.com/watch?v=example1',
  'Basic programming knowledge|High school mathematics',
  'Understand ML concepts|Build basic ML models|Apply algorithms to real data|Evaluate model performance',
  'Machine Learning',
  'English',
  100,
  true,
  'published'
),
(
  'Deep Learning Fundamentals', 
  'Prof. Michael Chen',
  4999.00,
  '12 weeks',
  'Intermediate',
  'Deep dive into neural networks, convolutional neural networks (CNNs), and recurrent neural networks (RNNs). Learn to build and train deep learning models using modern frameworks.',
  'https://www.youtube.com/watch?v=example2',
  'Introduction to Machine Learning|Python programming|Linear algebra basics',
  'Build deep neural networks|Implement CNNs for image recognition|Create RNNs for sequence data|Use TensorFlow and PyTorch',
  'Deep Learning',
  'English',
  75,
  true,
  'published'
),
(
  'AI for Beginners',
  'Dr. Emily Rodriguez',
  1999.00,
  '6 weeks', 
  'Beginner',
  'A gentle introduction to Artificial Intelligence concepts, applications, and impact on society. Perfect for non-technical audiences who want to understand AI.',
  'https://www.youtube.com/watch?v=example3',
  'No technical background required',
  'Understand AI concepts|Recognize AI applications|Appreciate AI ethics|Make informed AI decisions',
  'Artificial Intelligence',
  'English',
  150,
  true,
  'published'
),
(
  'Advanced Neural Networks',
  'Dr. Alex Thompson',
  6999.00,
  '16 weeks',
  'Advanced',
  'Advanced topics in neural networks including transformers, attention mechanisms, GANs, and cutting-edge architectures. Includes hands-on research projects.',
  'https://www.youtube.com/watch?v=example4',
  'Deep Learning Fundamentals|Strong mathematics background|Research experience preferred',
  'Implement transformer models|Build generative networks|Conduct AI research|Publish research findings',
  'Advanced AI',
  'English',
  25,
  true,
  'published'
)
ON CONFLICT (name) DO UPDATE SET
  instructor = EXCLUDED.instructor,
  fees = EXCLUDED.fees,
  duration = EXCLUDED.duration,
  level = EXCLUDED.level,
  description = EXCLUDED.description,
  video_link = EXCLUDED.video_link,
  prerequisites = EXCLUDED.prerequisites,
  learning_outcomes = EXCLUDED.learning_outcomes,
  category = EXCLUDED.category,
  language = EXCLUDED.language,
  max_students = EXCLUDED.max_students,
  includes_certificate = EXCLUDED.includes_certificate,
  status = EXCLUDED.status; 
